[tool.portray.mkdocs.theme]
name = "material"
favicon = "art/logo.png"
logo = "art/logo.png"
palette = {primary = "black", accent = "gray"}

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"